object fraGPSTrendLine: TfraGPSTrendLine
  Left = 0
  Top = 0
  Width = 677
  Height = 622
  TabOrder = 0
  TabStop = True
  OnResize = FrameResize
  object Splitter4: TSplitter
    Left = 0
    Top = 465
    Width = 677
    Height = 3
    Cursor = crVSplit
    Align = alTop
  end
  object Splitter5: TSplitter
    Left = 0
    Top = 269
    Width = 677
    Height = 3
    Cursor = crVSplit
    Align = alTop
  end
  object chtPointX: TChart
    Left = 0
    Top = 33
    Width = 677
    Height = 236
    AnimatedZoom = True
    AnimatedZoomSteps = 20
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = GB2312_CHARSET
    Title.Font.Color = clBlue
    Title.Font.Height = -14
    Title.Font.Name = #23435#20307
    Title.Font.Style = []
    Title.Text.Strings = (
      'X'#26041#21521#21464#24418#37327)
    BottomAxis.DateTimeFormat = 'yyyy-mm-dd hh:nn'
    BottomAxis.LabelsMultiLine = True
    BottomAxis.LabelsSize = 28
    BottomAxis.Title.Caption = #26102#38388
    BottomAxis.Title.Font.Charset = GB2312_CHARSET
    BottomAxis.Title.Font.Color = clBlack
    BottomAxis.Title.Font.Height = -11
    BottomAxis.Title.Font.Name = #23435#20307
    BottomAxis.Title.Font.Style = []
    Chart3DPercent = 100
    DepthAxis.Automatic = False
    DepthAxis.AutomaticMaximum = False
    DepthAxis.AutomaticMinimum = False
    DepthAxis.Maximum = 100.000000000000000000
    DepthAxis.Visible = True
    LeftAxis.ExactDateTime = False
    LeftAxis.LabelStyle = talValue
    LeftAxis.MinorTickCount = 5
    LeftAxis.Title.Caption = #21464#24418#37327'(mm)'
    LeftAxis.Title.Font.Charset = GB2312_CHARSET
    LeftAxis.Title.Font.Color = clBlack
    LeftAxis.Title.Font.Height = -11
    LeftAxis.Title.Font.Name = #23435#20307
    LeftAxis.Title.Font.Style = []
    Legend.ColorWidth = 20
    Legend.Font.Charset = GB2312_CHARSET
    Legend.Font.Color = clBlack
    Legend.Font.Height = -11
    Legend.Font.Name = #23435#20307
    Legend.Font.Style = []
    Legend.LegendStyle = lsSeries
    Legend.ShadowSize = 1
    View3D = False
    View3DOptions.Elevation = 336
    View3DOptions.Orthogonal = False
    View3DOptions.Rotation = 339
    View3DOptions.Zoom = 69
    Align = alTop
    BevelOuter = bvNone
    BevelWidth = 0
    Color = clWhite
    PopupMenu = popMethod
    TabOrder = 0
    TabStop = True
    OnContextPopup = chtPointXContextPopup
    OnMouseDown = chtPointXMouseDown
    OnMouseMove = chtPointXMouseMove
    OnMouseWheel = chtPointXMouseWheel
    object srsX: TLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = True
      SeriesColor = 16744448
      Title = 'PointX'
      LinePen.Width = 2
      Pointer.Brush.Color = clWhite
      Pointer.HorizSize = 3
      Pointer.InflateMargins = True
      Pointer.Pen.Color = 12615680
      Pointer.Pen.Width = 2
      Pointer.Style = psCircle
      Pointer.VertSize = 3
      Pointer.Visible = True
      XValues.DateTime = True
      XValues.Name = 'X'
      XValues.Multiplier = 1.000000000000000000
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1.000000000000000000
      YValues.Order = loNone
    end
  end
  object chtPointY: TChart
    Left = 0
    Top = 272
    Width = 677
    Height = 193
    AnimatedZoom = True
    AnimatedZoomSteps = 20
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = GB2312_CHARSET
    Title.Font.Color = clBlue
    Title.Font.Height = -14
    Title.Font.Name = #23435#20307
    Title.Font.Style = []
    Title.Text.Strings = (
      'Y'#26041#21521#21464#24418#37327)
    BottomAxis.DateTimeFormat = 'yyyy-MM-dd hh:nn'
    BottomAxis.LabelsMultiLine = True
    BottomAxis.LabelsSize = 28
    BottomAxis.Title.Caption = #26102#38388
    BottomAxis.Title.Font.Charset = GB2312_CHARSET
    BottomAxis.Title.Font.Color = clBlack
    BottomAxis.Title.Font.Height = -11
    BottomAxis.Title.Font.Name = #23435#20307
    BottomAxis.Title.Font.Style = []
    LeftAxis.LabelStyle = talValue
    LeftAxis.Title.Caption = #21464#24418#37327'(mm)'
    LeftAxis.Title.Font.Charset = GB2312_CHARSET
    LeftAxis.Title.Font.Color = clBlack
    LeftAxis.Title.Font.Height = -11
    LeftAxis.Title.Font.Name = #23435#20307
    LeftAxis.Title.Font.Style = []
    Legend.Font.Charset = GB2312_CHARSET
    Legend.Font.Color = clBlack
    Legend.Font.Height = -11
    Legend.Font.Name = #23435#20307
    Legend.Font.Style = []
    Legend.LegendStyle = lsSeries
    Legend.ShadowSize = 1
    View3D = False
    Align = alTop
    BevelOuter = bvNone
    Color = clWhite
    PopupMenu = popMethod
    TabOrder = 1
    TabStop = True
    OnContextPopup = chtPointYContextPopup
    OnMouseDown = chtPointYMouseDown
    OnMouseMove = chtPointYMouseMove
    OnMouseWheel = chtPointYMouseWheel
    object srsY: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = 8454143
      Title = 'PointY'
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = True
      XValues.Name = 'X'
      XValues.Multiplier = 1.000000000000000000
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1.000000000000000000
      YValues.Order = loNone
    end
  end
  object chtPointH: TChart
    Left = 0
    Top = 468
    Width = 677
    Height = 154
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = GB2312_CHARSET
    Title.Font.Color = clBlue
    Title.Font.Height = -14
    Title.Font.Name = #23435#20307
    Title.Font.Style = []
    Title.Text.Strings = (
      #39640#31243#21464#24418#37327)
    BottomAxis.DateTimeFormat = 'yyyy-MM-dd hh:nn'
    BottomAxis.LabelsMultiLine = True
    BottomAxis.LabelsSize = 28
    BottomAxis.Title.Caption = #26102#38388
    BottomAxis.Title.Font.Charset = GB2312_CHARSET
    BottomAxis.Title.Font.Color = clBlack
    BottomAxis.Title.Font.Height = -11
    BottomAxis.Title.Font.Name = #23435#20307
    BottomAxis.Title.Font.Style = []
    LeftAxis.Title.Caption = #21464#24418#37327'(mm)'
    LeftAxis.Title.Font.Charset = GB2312_CHARSET
    LeftAxis.Title.Font.Color = clBlack
    LeftAxis.Title.Font.Height = -11
    LeftAxis.Title.Font.Name = #23435#20307
    LeftAxis.Title.Font.Style = []
    Legend.Font.Charset = GB2312_CHARSET
    Legend.Font.Color = clBlack
    Legend.Font.Height = -11
    Legend.Font.Name = #23435#20307
    Legend.Font.Style = []
    Legend.LegendStyle = lsSeries
    View3D = False
    Align = alClient
    BevelOuter = bvNone
    Color = clWhite
    PopupMenu = popMethod
    TabOrder = 2
    TabStop = True
    OnContextPopup = chtPointHContextPopup
    OnMouseDown = chtPointHMouseDown
    OnMouseMove = chtPointHMouseMove
    OnMouseWheel = chtPointHMouseWheel
    object srsH: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clYellow
      Title = 'PointH'
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = True
      XValues.Name = 'X'
      XValues.Multiplier = 1.000000000000000000
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1.000000000000000000
      YValues.Order = loNone
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 677
    Height = 33
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvNone
    BorderWidth = 1
    TabOrder = 3
    object Label1: TLabel
      Left = 8
      Top = 8
      Width = 48
      Height = 13
      Caption = #36215#22987#26102#38388
    end
    object Label2: TLabel
      Left = 152
      Top = 8
      Width = 48
      Height = 13
      Caption = #25130#27490#26102#38388
    end
    object dtpTL_BeginDate: TDateTimePicker
      Left = 60
      Top = 4
      Width = 81
      Height = 21
      Date = 40295.153540937500000000
      Time = 40295.153540937500000000
      TabOrder = 0
    end
    object dtpTL_EndDate: TDateTimePicker
      Left = 200
      Top = 4
      Width = 85
      Height = 21
      Date = 40295.154166840280000000
      Time = 40295.154166840280000000
      TabOrder = 1
    end
    object chkShowDataPoint: TCheckBox
      Left = 292
      Top = 8
      Width = 61
      Height = 17
      Caption = #25968#25454#28857
      TabOrder = 2
      OnClick = chkShowDataPointClick
    end
    object chkShowDataMark: TCheckBox
      Left = 360
      Top = 8
      Width = 61
      Height = 17
      Caption = #25968#20540#31614
      TabOrder = 3
      OnClick = chkShowDataMarkClick
    end
  end
  object popMethod: TPopupMenu
    Left = 180
    Top = 84
    object miEqualDivisionArea: TMenuItem
      Caption = #31561#20998#32472#22270#21306
      OnClick = miEqualDivisionAreaClick
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object miCopyBitmap: TMenuItem
      Caption = #25335#36125#20026#20301#22270
      OnClick = miCopyBitmapClick
    end
    object miCopyMetaFile: TMenuItem
      Caption = #25335#36125#20026#22270#20803
      OnClick = miCopyMetaFileClick
    end
  end
end
